--

- hosts: all
  become: true
  pre_tasks:

  - name: install updates Ubuntu
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install updates Centos
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    package:
      name: samba
      state: latest
